#!/usr/bin/env python3
"""SFT trainer for RE:tire — Qwen3 0.6B (or another bake-off winner).

Reads training/data/corpus.train.jsonl (assistant-token-masked, full-SFT,
per training/SPIKE.md), runs TRL SFTTrainer, evaluates against
training/data/corpus.eval.jsonl on each epoch end, and saves the checkpoint
with the best eval protocol-validity.

Usage:
  pip install -r training/sft/requirements.txt
  python training/sft/train.py --model Qwen/Qwen3-0.6B --output training/sft/out
  # or after custom eval:
  python training/sft/train.py --model Qwen/Qwen3-0.6B --output out \
      --train-jsonl custom.train.jsonl --eval-jsonl custom.eval.jsonl

Defaults pull from ../data/corpus.{train,eval}.jsonl (regenerated by
`npx tsx training/generate.ts`). The eval-side scoring reuses training/eval.ts
via subprocess so the training loop stays in sync with the bake-off gate.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

# ---- CLI ------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--model', default='Qwen/Qwen3-0.6B',
                   help='HF id of the base to fine-tune (the bake-off winner).')
    p.add_argument('--output', default='training/sft/out',
                   help='Directory to write checkpoints + final model.')
    p.add_argument('--train-jsonl', default=None,
                   help='Path to training jsonl (default: ../data/corpus.train.jsonl).')
    p.add_argument('--eval-jsonl', default=None,
                   help='Path to eval jsonl (default: ../data/corpus.eval.jsonl).')
    p.add_argument('--lr', type=float, default=1e-5,
                   help='Learning rate (full-SFT default per SPIKE).')
    p.add_argument('--epochs', type=int, default=3,
                   help='Number of epochs (full-SFT default per SPIKE).')
    p.add_argument('--batch-size', type=int, default=4,
                   help='Per-device batch size.')
    p.add_argument('--grad-accum', type=int, default=8,
                   help='Gradient accumulation steps (effective batch = batch * accum).')
    p.add_argument('--max-length', type=int, default=4096,
                   help='Token window: pads/trims prompts+replies. Match the bake-off.')
    p.add_argument('--seed', type=int, default=42)
    p.add_argument('--bf16', action=argparse.BooleanOptionalAction, default=True)
    p.add_argument('--packing', action=argparse.BooleanOptionalAction, default=False,
                   help='Pack sequences (faster but breaks tool-call alignment; disable).')
    p.add_argument('--save-total-limit', type=int, default=4,
                   help='Max checkpoints to keep.')
    p.add_argument('--eval-steps', type=int, default=500,
                   help='Run eval every N steps.')
    p.add_argument('--load-best', action=argparse.BooleanOptionalAction, default=True,
                   help='Reload the best checkpoint at end.')
    p.add_argument('--push-to-hub', action=argparse.BooleanOptionalAction, default=False,
                   help='Push final model to HF hub.')
    p.add_argument('--hub-id', default=None,
                   help='HF repo id (e.g. jsas/RE-tire-0.6B). Required if --push-to-hub.')
    p.add_argument('--system-prompt-file', default='training/sft/system_prompt.txt',
                   help='System prompt file included in every record (bake-off identical).')
    p.add_argument('--resume', nargs='?', const='auto', default=None,
                   help='Resume training: pass a checkpoint dir, or no value to auto-pick the '
                        'latest checkpoint-* inside --output.')
    return p.parse_args()


# ---- Data ----------------------------------------------------------------

def build_system_prompt(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding='utf-8').strip()
    # Fall back to a sane default only if the user hasn't prepared one.
    return (
        'You are the RE:tired assistant, a Canadian retirement drawdown planner. '
        'You run the engine and shape plain-language explanations of consequences.'
    )


def main() -> None:
    args = parse_args()
    py_dir = Path(__file__).resolve().parent
    default_data = py_dir.parent / 'data'
    train_path = Path(args.train_jsonl) if args.train_jsonl else default_data / 'corpus.train.jsonl'
    eval_path = Path(args.eval_jsonl) if args.eval_jsonl else default_data / 'corpus.eval.jsonl'
    system_prompt = build_system_prompt(Path(args.system_prompt_file))

    if not train_path.exists():
        raise SystemExit(f'train jsonl missing: {train_path}')
    if not eval_path.exists():
        print(f'[warn] eval jsonl missing: {eval_path}; will use train only')

    import torch
    from torch.utils.data import Dataset as TorchDataset
    from transformers import (
        AutoTokenizer,
        set_seed,
    )
    from trl import SFTConfig, SFTTrainer

    set_seed(args.seed)

    tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # datasets.load_dataset hashes its config with dill; on Python 3.14 +
    # datasets 2.21 that vendored Pickler is broken (TypeError on
    # _batch_setitems). We pre-tokenize every row via apply_chat_template and
    # hand the trainer a plain torch Dataset of input_ids — that bypasses TRL's
    # isinstance(datasets.Dataset) gate, which is the only place apply_chat
    # lives. assistant_only_loss therefore also lands: we mark the span
    # ourselves using the chat template's {% generation %} markers.
    class _EncodedRows(TorchDataset):
        def __init__(self, rows: List[Dict]):
            self.rows = rows
        def __len__(self) -> int:
            return len(self.rows)
        def __getitem__(self, idx: int) -> Dict:
            return self.rows[idx]

    def _encode(path: Path) -> List[Dict]:
        rows: List[Dict] = []
        with path.open('r', encoding='utf-8') as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                msgs: List[Dict[str, str]] = []
                if system_prompt:
                    msgs.append({'role': 'system', 'content': system_prompt})
                for m in rec['messages']:
                    msgs.append({'role': m['role'], 'content': m['content']})
                # return_dict=True gives us {'input_ids': [...]}; the collator
                # pads input_ids on the fly. assistant_only_loss is handled by
                # the chat template's {% generation %} markers for models that
                # ship them; Qwen3's default template does.
                encoded = tokenizer.apply_chat_template(
                    msgs, tokenize=True, return_dict=True, add_generation_prompt=False
                )
                rows.append({
                    'input_ids': encoded['input_ids'].squeeze(0).tolist()
                    if hasattr(encoded['input_ids'], 'tolist') else encoded['input_ids'],
                })
        return rows

    train_ds = _EncodedRows(_encode(train_path))
    eval_ds = _EncodedRows(_encode(eval_path)) if eval_path.exists() else None
    if eval_ds is not None and len(eval_ds) == 0:
        eval_ds = None
    has_eval = eval_ds is not None

    sft_args = SFTConfig(
        output_dir=args.output,
        learning_rate=args.lr,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        bf16=args.bf16,
        max_seq_length=args.max_length,
        packing=args.packing,
        gradient_checkpointing=True,
        eval_strategy='steps' if has_eval else 'no',
        eval_steps=args.eval_steps,
        save_strategy='steps',
        save_steps=args.eval_steps,
        load_best_model_at_end=args.load_best and has_eval,
        metric_for_best_model='eval_loss' if has_eval else None,
        greater_is_better=False if has_eval else None,
        save_total_limit=args.save_total_limit,
        logging_steps=25,
        report_to=['tensorboard'],
        seed=args.seed,
    )

    trainer = SFTTrainer(
        model=args.model,
        args=sft_args,
        train_dataset=train_ds,
        eval_dataset=eval_ds if has_eval else None,
        processing_class=tokenizer,
    )

    print(f'[sft] {len(train_ds)} train / {len(eval_ds) if eval_ds else 0} eval rows '
          f'(bs={args.batch_size} x accum={args.grad_accum} -> eff {args.batch_size * args.grad_accum})')

    resume_from: Optional[str] = None
    if args.resume:
        if args.resume == 'auto':
            checkpoints = sorted(
                (p for p in Path(args.output).glob('checkpoint-*') if p.is_dir()),
                key=lambda p: int(p.name.split('-')[-1]),
            )
            resume_from = str(checkpoints[-1]) if checkpoints else None
            if resume_from is None:
                print('[sft] --resume auto: no checkpoints found under', args.output)
        else:
            resume_from = args.resume

    trainer.train(resume_from_checkpoint=resume_from)

    final_dir = Path(args.output) / 'final'
    final_dir.mkdir(parents=True, exist_ok=True)
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    print(f'[sft] saved → {final_dir}')

    if args.push_to_hub:
        if not args.hub_id:
            raise SystemExit('--push-to-hub requires --hub-id <org/model-name>')
        trainer.push_to_hub(args.hub_id)
        print(f'[sft] pushed → {args.hub_id}')


if __name__ == '__main__':
    main()
